# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build Totem"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left","totem_right","settings_reset"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      kconfig: '["CONFIG_ZMK_POINTING=y\nCONFIG_ZMK_SLEEP=y"]'
      branches: '["zmkfirmware/zmk/main"]'
